# Generated by Django 3.1.5 on 2021-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
